const data = {
  sales: {
    data: [
      {
        id: "o1",
        product: "3W ACE",
        target: "50",
        achieved: "40",
        target_left: "10",
      },
      {
        id: "o2",
        product: "3W Pro",
        target: "50",
        achieved: "40",
        target_left: "10",
      },
      {
        id: "o3",
        product: "4W ACE",
        target: "50",
        achieved: "40",
        target_left: "10",
      },
      {
        id: "o4",
        product: "4W Pro",
        target: "50",
        achieved: "40",
        target_left: "10",
      },
    ],
    total: 4,
  },
  inventory: {
    data: [
      {
        id: 1,
        model: "3W-ACE-SKU9875",
        price: "Rs. 35620",
        addedOn: "06/05/2020",
        imageURL:
          "https://images.unsplash.com/photo-1558981403-c5f9899a28bc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80",
        pName: "ACE",
        SKU: "SKU35956",
        mDate: "02/05/2019",
        tankID: "TN98745",
        tankCapacity: "20",
        iAging: "5 days",
      },
      {
        id: 2,
        model: "3W-ACE-SKU9875",
        price: "Rs. 35620",
        addedOn: " 06/05/2020",
        pName: "ACE",
        SKU: "SKU35956",
        mDate: "02/05/2019",
        tankID: "TN98745",
        tankCapacity: "20",
        iAging: "5 days",
        imageURL:
          "https://images.unsplash.com/photo-1558981403-c5f9899a28bc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80",
      },
      {
        id: 3,
        model: "3W-ACE-SKU9875",
        price: "Rs. 35620",
        addedOn: " 06/05/2020",
        pName: "ACE",
        SKU: "SKU35956",
        mDate: "02/05/2019",
        tankID: "TN98745",
        tankCapacity: "20",
        iAging: "5 days",
        imageURL:
          "https://images.unsplash.com/photo-1558981403-c5f9899a28bc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80",
      },
      {
        id: 4,
        model: "3W-ACE-SKU9875",
        price: "Rs. 35620",
        addedOn: " 06/05/2020",
        pName: "ACE",
        SKU: "SKU35956",
        mDate: "02/05/2019",
        tankID: "TN98745",
        tankCapacity: "20",
        iAging: "5 days",
        imageURL:
          "https://images.unsplash.com/photo-1558981403-c5f9899a28bc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80",
      },
    ],
    total: 4,
  },

  support: {
    data: [
      {
        id: "#1",
        title: "Purchase Hang",
        date: "2020-05-26",
        status: "opened",
      },
      {
        id: "#2",
        title: "Purchase Hang",
        date: "2020-05-26",
        status: "opened",
      },
      {
        id: "#3",
        title: "Purchase Hang",
        date: "2020-05-26",
        status: "closed",
      },
      {
        id: "#4",
        title: "Purchase Hang",
        date: "2020-05-26",
        status: "opened",
      },
    ],
    total: 4,
  },
  profile: {
    data: [
      {
        distID: 2555,
        name: "Sachin T.",
        email: "Sachin@gmail.com",
        phoneNumber: "12346423423",
        whatsApp: "12346423423",
        address: "Indiabulls, Lower Parel",
        pincode: "411093",
        city: "Mumbai",
        state: "MH",
        country: "INDIA",
      },
    ],
    total: 1,
  },
  leads: {
    data: [
      {
        distID: 2555,
        name: "Sachin T. Assined",
        email: "SachinDealer@gmail.com",
        phoneNumber: "12346423423",
        whatsApp: "12346423423",
        assignedDealer: "Jack",
        address: "Indiabulls, Lower Parel",
        pincode: "411093",
        city: "Mumbai",
        state: "MH",
        isDealer: false,
        assigned: true,
        country: "INDIA",
        leadRating: "3.5"
      },
      {
        distID: 2555,
        name: "Sachin T. Dealer",
        email: "Sachin@gmail.com",
        phoneNumber: "12346423423",
        whatsApp: "12346423423",
        address: "Indiabulls, Lower Parel",
        assignedDealer: "Jack",
        pincode: "411093",
        city: "Mumbai",
        state: "MH",
        country: "INDIA",
        isDealer: true,
        leadRating: "3.5"
      },
      {
        distID: 2555,
        name: "Sachin T. Assined and Dealer",
        email: "Sachin@gmail.com",
        phoneNumber: "12346423423",
        whatsApp: "12346423423",
        address: "Indiabulls, Lower Parel",
        pincode: "411093",
        city: "Mumbai",
        assignedDealer: "Jack",
        vehicleType: "4W",
        state: "MH",
        assigned: true,
        country: "INDIA",
        kitEnq: "PRO",
        isDealer: true,
        leadRating: "3.5"
      },
      {
        distID: 2555,
        name: "Sachin T. Dealer",
        email: "Sachin@gmail.com",
        phoneNumber: "12346423423",
        whatsApp: "12346423423",
        address: "Indiabulls, Lower Parel",
        pincode: "411093",
        city: "Mumbai",
        state: "MH",
        country: "INDIA",
        isDealer: false,
        assigned: false,
        leadRating: "3.5"
      },
      {
        distID: 2555,
        name: "Sachin T.",
        email: "Sachin@gmail.com",
        phoneNumber: "12346423423",
        whatsApp: "12346423423",
        address: "Indiabulls, Lower Parel",
        pincode: "411093",
        city: "Mumbai",
        state: "MH",
        isDealer: false,
        assigned: true,
        country: "INDIA",
        leadRating: "3.5"
      },
    ],
    total: 1,
  },
  rto: {
    data: [
      {
        rtos: {
          id: "#1",
          title: "RTO Document",
          status: "Submitted",
          make: "Honda",
          type: "4 Wheeler",
          address: "ML 243, AL",
          phone: "20200526",
          fullname: "Sanchi Kumar",
          num: "2020",
          model: "Ciaz",
        },
      },
      {
        rtos: {
          id: "#2",
          make: "Honda",
          title: "Insurance Documents",
          status: "Document Collected",
          type: "4 Wheeler",
          address: "ML 243, AL",
          phone: "20200526",
          fullname: "Sanchi Kumar",
          num: "2020",
          model: "Ciaz",
        },
      },
      {
        rtos: {
          id: "#3",
          title: "Purchase Hang",
          make: "Honda",
          type: "4 Wheeler",
          address: "ML 243, AL",
          phone: "20200526",
          fullname: "Sanchi Kumar",
          num: "2020",
          model: "Ciaz",
        },
      },
      {
        rtos: {
          id: "#4",
          title: "Purchase Hang",
          make: "Honda",
          type: "4 Wheeler",
          address: "ML 243, AL",
          phone: "20200526",
          fullname: "Sanchi Kumar",
          num: "2020",
          model: "Ciaz",
        },
      },
    ],
    total: 4,
  },
  customers: {
    data: [
      {
        id: 1,
        firstName: "Sachin",
        middleName: "",
        lastName: "T",
        mobileNumber: "123566666",
        productPurchased: "3W Pro",
        dealerRating: "3.5",
      },
      {
        id: 2,
        firstName: "Sachin",
        middleName: "",
        lastName: "T",
        mobileNumber: "123566666",
        productPurchased: "3W Pro",
        dealerRating: "3.5",
      },
      {
        id: 3,

        firstName: "Sachin",
        middleName: "",
        lastName: "T",
        mobileNumber: "123566666",
        productPurchased: "3W Pro",
        dealerRating: "3.5",
      },
      {
        id: 4,

        firstName: "Sachin",
        middleName: "",
        lastName: "T",
        mobileNumber: "123566666",
        productPurchased: "3W Pro",
        dealerRating: "3.5",
      },
      {
        id: 5,

        firstName: "Sachin",
        middleName: "",
        lastName: "T",
        mobileNumber: "123566666",
        productPurchased: "3W Pro",
        dealerRating: "3.5",
      },
    ],
    total: 5,
  },
  dealers: [
    {
      id: 1,
      name: "Leanne Graham",
      username: "Bret",
      email: "Sincere@april.biz",
      address: {
        street: "Kulas Light",
        suite: "Apt. 556",
        city: "Gwenborough",
        zipcode: "92998-3874",
        geo: {
          lat: "-37.3159",
          lng: "81.1496",
        },
      },
      phone: "1-770-736-8031 x56442",
      website: "hildegard.org",
      company: {
        name: "Romaguera-Crona",
        catchPhrase: "Multi-layered client-server neural-net",
        bs: "harness real-time e-markets",
      },
    },
    {
      id: 2,
      name: "Ervin Howell",
      username: "Antonette",
      email: "Shanna@melissa.tv",
      address: {
        street: "Victor Plains",
        suite: "Suite 879",
        city: "Wisokyburgh",
        zipcode: "90566-7771",
        geo: {
          lat: "-43.9509",
          lng: "-34.4618",
        },
      },
      phone: "010-692-6593 x09125",
      website: "anastasia.net",
      company: {
        name: "Deckow-Crist",
        catchPhrase: "Proactive didactic contingency",
        bs: "synergize scalable supply-chains",
      },
    },
    {
      id: 3,
      name: "Clementine Bauch",
      username: "Samantha",
      email: "Nathan@yesenia.net",
      address: {
        street: "Douglas Extension",
        suite: "Suite 847",
        city: "McKenziehaven",
        zipcode: "59590-4157",
        geo: {
          lat: "-68.6102",
          lng: "-47.0653",
        },
      },
      phone: "1-463-123-4447",
      website: "ramiro.info",
      company: {
        name: "Romaguera-Jacobson",
        catchPhrase: "Face to face bifurcated interface",
        bs: "e-enable strategic applications",
      },
    },
    {
      id: 4,
      name: "Patricia Lebsack",
      username: "Karianne",
      email: "Julianne.OConner@kory.org",
      address: {
        street: "Hoeger Mall",
        suite: "Apt. 692",
        city: "South Elvis",
        zipcode: "53919-4257",
        geo: {
          lat: "29.4572",
          lng: "-164.2990",
        },
      },
      phone: "493-170-9623 x156",
      website: "kale.biz",
      company: {
        name: "Robel-Corkery",
        catchPhrase: "Multi-tiered zero tolerance productivity",
        bs: "transition cutting-edge web services",
      },
    },
    {
      id: 5,
      name: "Chelsey Dietrich",
      username: "Kamren",
      email: "Lucio_Hettinger@annie.ca",
      address: {
        street: "Skiles Walks",
        suite: "Suite 351",
        city: "Roscoeview",
        zipcode: "33263",
        geo: {
          lat: "-31.8129",
          lng: "62.5342",
        },
      },
      phone: "(254)954-1289",
      website: "demarco.info",
      company: {
        name: "Keebler LLC",
        catchPhrase: "User-centric fault-tolerant solution",
        bs: "revolutionize end-to-end systems",
      },
    },
    {
      id: 6,
      name: "Mrs. Dennis Schulist",
      username: "Leopoldo_Corkery",
      email: "Karley_Dach@jasper.info",
      address: {
        street: "Norberto Crossing",
        suite: "Apt. 950",
        city: "South Christy",
        zipcode: "23505-1337",
        geo: {
          lat: "-71.4197",
          lng: "71.7478",
        },
      },
      phone: "1-477-935-8478 x6430",
      website: "ola.org",
      company: {
        name: "Considine-Lockman",
        catchPhrase: "Synchronised bottom-line interface",
        bs: "e-enable innovative applications",
      },
    },
    {
      id: 7,
      name: "Kurtis Weissnat",
      username: "Elwyn.Skiles",
      email: "Telly.Hoeger@billy.biz",
      address: {
        street: "Rex Trail",
        suite: "Suite 280",
        city: "Howemouth",
        zipcode: "58804-1099",
        geo: {
          lat: "24.8918",
          lng: "21.8984",
        },
      },
      phone: "210.067.6132",
      website: "elvis.io",
      company: {
        name: "Johns Group",
        catchPhrase: "Configurable multimedia task-force",
        bs: "generate enterprise e-tailers",
      },
    },
    {
      id: 8,
      name: "Nicholas Runolfsdottir V",
      username: "Maxime_Nienow",
      email: "Sherwood@rosamond.me",
      address: {
        street: "Ellsworth Summit",
        suite: "Suite 729",
        city: "Aliyaview",
        zipcode: "45169",
        geo: {
          lat: "-14.3990",
          lng: "-120.7677",
        },
      },
      phone: "586.493.6943 x140",
      website: "jacynthe.com",
      company: {
        name: "Abernathy Group",
        catchPhrase: "Implemented secondary concept",
        bs: "e-enable extensible e-tailers",
      },
    },
    {
      id: 9,
      name: "Glenna Reichert",
      username: "Delphine",
      email: "Chaim_McDermott@dana.io",
      address: {
        street: "Dayna Park",
        suite: "Suite 449",
        city: "Bartholomebury",
        zipcode: "76495-3109",
        geo: {
          lat: "24.6463",
          lng: "-168.8889",
        },
      },
      phone: "(775)976-6794 x41206",
      website: "conrad.com",
      company: {
        name: "Yost and Sons",
        catchPhrase: "Switchable contextually-based project",
        bs: "aggregate real-time technologies",
      },
    },
    {
      id: 10,
      name: "Clementina DuBuque",
      username: "Moriah.Stanton",
      email: "Rey.Padberg@karina.biz",
      address: {
        street: "Kattie Turnpike",
        suite: "Suite 198",
        city: "Lebsackbury",
        zipcode: "31428-2261",
        geo: {
          lat: "-38.2386",
          lng: "57.2232",
        },
      },
      phone: "024-648-3804",
      website: "ambrose.net",
      company: {
        name: "Hoeger LLC",
        catchPhrase: "Centralized empowering task-force",
        bs: "target end-to-end models",
      },
    },
  ],
};

export default data;
